docker

diff --git a/docker/apache-php/Dockerfile b/docker/apache-php/Dockerfile
--- a/docker/apache-php/Dockerfile
+++ b/docker/apache-php/Dockerfile
@@ -29,25 +29,102 @@ RUN yum -y install \
 	php-pear-CAS \
 	cronie
  
-RUN yum -y clean all
+RUN yum -y clean all && rm -rf /var/cache/yum
 
-ADD 99-glpi.ini /etc/php.d/
-ADD timezone.ini /etc/php.d/
-ADD glpi.conf /etc/httpd/conf.d/
+RUN { \
+	echo 'memory_limit = 64M;'; \
+	echo 'file_uploads = on ;'; \
+	echo 'max_execution_time = 600 ;'; \
+	echo 'register_globals = off ;'; \
+	echo 'magic_quotes_sybase = off ;'; \
+	echo 'session.auto_start = off ;'; \
+	echo 'session.use_trans_sid = 0 ;'; \
+	echo; \
+    } > /etc/php.d/99-glpi.ini
+
+RUN { \
+	echo '[Date]'; \
+	echo 'date.timezone = America/Fortaleza ; '; \
+	echo; \
+    } > /etc/php.d/timezone.ini
+
+RUN { \
+	echo 'apc.enable_cli=1'; \
+	echo ; \
+    } >> /etc/php.d/40-apcu.ini
+
+RUN { \
+	echo '    <Directory /var/www/html/>'; \
+	echo '        Options Indexes FollowSymLinks'; \
+	echo '        AllowOverride All'; \
+	echo '        Require all granted'; \
+	echo '    </Directory>'; \
+	echo 'ErrorLog /dev/stderr'; \
+	echo 'TransferLog /dev/stdout'; \
+	echo; \
+    } > /etc/httpd/conf.d/glpi.conf
+
+RUN { \
+	echo '*/2 * * * * root cd /var/www/html/front && /usr/bin/php cron.php'; \
+	echo '*/5 * * * * root cd /var/www/html/front && /usr/bin/php cron.php --forcequeudnotification'; \
+	echo; \
+    } > /var/spool/cron/root
+
+
+RUN { \
+	echo '#!/bin/bash'; \
+	echo 'if [ -e /var/www/html/install/install.php ]; then'; \
+	echo '  echo "Deploy DB with cliinstall.php. This procedure delay 10 minutes. Please wait..." '; \
+	echo '  php /var/www/html/scripts/cliinstall.php --host=mariadb --db=glpi --user=glpi --pass=glpi --lang=pt_BR;';\
+	echo '  rm -rf /var/www/html/install/install.php'; \
+	echo 'fi'; \
+	echo ; \
+	echo 'crond'; \
+	echo 'status=$?'; \
+	echo 'if [ $status -ne 0 ]; then'; \
+	echo '  echo "Failed to start my_first_process: $status"'; \
+	echo '  exit $status'; \
+	echo 'fi';  \
+	echo ; \
+	echo 'httpd -D FOREGROUND'; \
+	echo 'status=$?'; \
+	echo 'if [ $status -ne 0 ]; then'; \
+	echo '  echo "Failed to start my_second_process: $status"'; \
+	echo '  exit $status'; \
+	echo 'fi'; \
+	echo ; \
+	echo 'while sleep 60; do'; \
+	echo '  ps aux |grep crond |grep -q -v grep'; \
+	echo '  PROCESS_1_STATUS=$?'; \
+	echo '  ps aux |grep httpd |grep -q -v grep'; \
+	echo '  PROCESS_2_STATUS=$?'; \
+	echo '  if [ $PROCESS_1_STATUS -ne 0 -o $PROCESS_2_STATUS -ne 0 ]; then'; \
+	echo '    echo "One of the processes has already exited."'; \
+	echo '    exit 1'; \
+	echo '  fi'; \
+	echo 'done'; \
+	echo; \
+    } > /entrypoint.sh && chmod 755 /entrypoint.sh
+
+
+
+
+
+# RUN sed -i '/session required pam_loginuid.so/d' /etc/pamd.d/crond
+
 ADD https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.tgz /var/www/html/
+
 
 RUN tar -zxf /var/www/html/glpi-9.3.tgz -C /var/www/html/ \
 	&& rm -rf /var/www/html/glpi/glpi-9.3.tgz \
 	&& mv /var/www/html/glpi/* /var/www/html/ \
-	&& chown -R apache:apache /var/www/html
+	&& chown -Rf apache:apache /var/www/html
 
 
-VOLUME ["/var/www/html", "/etc/httpd", "/etc/php.d"]
+VOLUME ["/var/www/html"]
 
 EXPOSE 80/tcp 443/tcp
 
-# ENTRYPOINT ["php", "/var/www/html/scripts/cliinstall.php", "--host=mariadb", "--db=glpi", "--user=glpi", "--pass=glpi", "--lang=pt_BR"]
-# ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
-# ENTRYPOINT ["crond"]
-ENTRYPOINT ["httpd"]
-CMD ["-D", "FOREGROUND"]
+ENTRYPOINT ["/entrypoint.sh"]
+
+# CMD ["-D", "FOREGROUND"]
